// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.0
// source: redgrouse_api.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "redgrouse.api";

export interface ApiErrorBody {
  error: string;
  code?: string | undefined;
}

export interface UploadMetadata {
  uploadId: string;
  filename: string;
  rowCount: number;
  title: string;
  dataVersion: number;
}

export interface UploadResponse {
  uploadId: string;
  filename: string;
  rowCount: number;
  editToken: string;
  title: string;
  dataVersion: number;
}

export interface UpdateResponse {
  uploadId: string;
  filename: string;
  rowCount: number;
  title: string;
  dataVersion: number;
}

export interface DeleteResponse {
  deleted: boolean;
}

export interface CountResponse {
  count: number;
  dataVersion: number;
}

export interface FieldMetadata {
  name: string;
  label: string;
  fieldType: string;
}

export interface FieldMetadataList {
  fields: FieldMetadata[];
}

export interface FieldValues {
  field: string;
  values: string[];
  dataVersion: number;
}

export interface BboxResponse {
  minLng: number;
  minLat: number;
  maxLng: number;
  maxLat: number;
  dataVersion: number;
}

export interface Species {
  commonName: string;
  scientificName: string;
}

export interface Sighting {
  id: number;
  commonNameIndex?: number | undefined;
  count?: number | undefined;
  latitude: number;
  longitude: number;
  countryCode?: string | undefined;
  regionCode?: string | undefined;
  observedAt: string;
}

export interface GroupedSighting {
  commonNameIndex?: number | undefined;
  countryCode?: string | undefined;
  observedAt?: string | undefined;
  count: number;
  speciesCount: number;
}

export interface SightingsResponse {
  nameIndex: Species[];
  sightings: Sighting[];
  groups: GroupedSighting[];
  total: number;
  dataVersion: number;
  nextCursor?: string | undefined;
}

export interface VersionInfo {
  gitHash: string;
  buildDate: string;
  rustcVersion: string;
}

export interface SpeciesCount {
  commonName: string;
  scientificName: string;
  count: number;
}

export interface CountryStats {
  countryCode: string;
  sightings: number;
  lifers: number;
}

export interface TimelinePoint {
  date: string;
  count: number;
}

export interface StatsResponse {
  totalSightings: number;
  totalLifers: number;
  totalYearTicks: number;
  totalCountryTicks: number;
  totalSpecies: number;
  totalCountries: number;
  totalRegions: number;
  hoursBirdingMinutes: number;
  firstSightingDate?: string | undefined;
  latestSightingDate?: string | undefined;
  topSpecies: SpeciesCount[];
  countryStats: CountryStats[];
  dataVersion: number;
  totalIndividuals: number;
  totalDistanceKm?: number | undefined;
  lifersTimeline: TimelinePoint[];
  sightingsTimeline: TimelinePoint[];
  longestStreakDays: number;
}

function createBaseApiErrorBody(): ApiErrorBody {
  return { error: "", code: undefined };
}

export const ApiErrorBody: MessageFns<ApiErrorBody> = {
  encode(message: ApiErrorBody, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== "") {
      writer.uint32(10).string(message.error);
    }
    if (message.code !== undefined) {
      writer.uint32(18).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApiErrorBody {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApiErrorBody();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ApiErrorBody>, I>>(base?: I): ApiErrorBody {
    return ApiErrorBody.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApiErrorBody>, I>>(object: I): ApiErrorBody {
    const message = createBaseApiErrorBody();
    message.error = object.error ?? "";
    message.code = object.code ?? undefined;
    return message;
  },
};

function createBaseUploadMetadata(): UploadMetadata {
  return { uploadId: "", filename: "", rowCount: 0, title: "", dataVersion: 0 };
}

export const UploadMetadata: MessageFns<UploadMetadata> = {
  encode(message: UploadMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uploadId !== "") {
      writer.uint32(10).string(message.uploadId);
    }
    if (message.filename !== "") {
      writer.uint32(18).string(message.filename);
    }
    if (message.rowCount !== 0) {
      writer.uint32(24).int64(message.rowCount);
    }
    if (message.title !== "") {
      writer.uint32(34).string(message.title);
    }
    if (message.dataVersion !== 0) {
      writer.uint32(40).int64(message.dataVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uploadId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rowCount = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dataVersion = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UploadMetadata>, I>>(base?: I): UploadMetadata {
    return UploadMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadMetadata>, I>>(object: I): UploadMetadata {
    const message = createBaseUploadMetadata();
    message.uploadId = object.uploadId ?? "";
    message.filename = object.filename ?? "";
    message.rowCount = object.rowCount ?? 0;
    message.title = object.title ?? "";
    message.dataVersion = object.dataVersion ?? 0;
    return message;
  },
};

function createBaseUploadResponse(): UploadResponse {
  return { uploadId: "", filename: "", rowCount: 0, editToken: "", title: "", dataVersion: 0 };
}

export const UploadResponse: MessageFns<UploadResponse> = {
  encode(message: UploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uploadId !== "") {
      writer.uint32(10).string(message.uploadId);
    }
    if (message.filename !== "") {
      writer.uint32(18).string(message.filename);
    }
    if (message.rowCount !== 0) {
      writer.uint32(24).int64(message.rowCount);
    }
    if (message.editToken !== "") {
      writer.uint32(34).string(message.editToken);
    }
    if (message.title !== "") {
      writer.uint32(42).string(message.title);
    }
    if (message.dataVersion !== 0) {
      writer.uint32(48).int64(message.dataVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uploadId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rowCount = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.editToken = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.dataVersion = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UploadResponse>, I>>(base?: I): UploadResponse {
    return UploadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadResponse>, I>>(object: I): UploadResponse {
    const message = createBaseUploadResponse();
    message.uploadId = object.uploadId ?? "";
    message.filename = object.filename ?? "";
    message.rowCount = object.rowCount ?? 0;
    message.editToken = object.editToken ?? "";
    message.title = object.title ?? "";
    message.dataVersion = object.dataVersion ?? 0;
    return message;
  },
};

function createBaseUpdateResponse(): UpdateResponse {
  return { uploadId: "", filename: "", rowCount: 0, title: "", dataVersion: 0 };
}

export const UpdateResponse: MessageFns<UpdateResponse> = {
  encode(message: UpdateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uploadId !== "") {
      writer.uint32(10).string(message.uploadId);
    }
    if (message.filename !== "") {
      writer.uint32(18).string(message.filename);
    }
    if (message.rowCount !== 0) {
      writer.uint32(24).int64(message.rowCount);
    }
    if (message.title !== "") {
      writer.uint32(34).string(message.title);
    }
    if (message.dataVersion !== 0) {
      writer.uint32(40).int64(message.dataVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uploadId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rowCount = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dataVersion = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UpdateResponse>, I>>(base?: I): UpdateResponse {
    return UpdateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateResponse>, I>>(object: I): UpdateResponse {
    const message = createBaseUpdateResponse();
    message.uploadId = object.uploadId ?? "";
    message.filename = object.filename ?? "";
    message.rowCount = object.rowCount ?? 0;
    message.title = object.title ?? "";
    message.dataVersion = object.dataVersion ?? 0;
    return message;
  },
};

function createBaseDeleteResponse(): DeleteResponse {
  return { deleted: false };
}

export const DeleteResponse: MessageFns<DeleteResponse> = {
  encode(message: DeleteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deleted !== false) {
      writer.uint32(8).bool(message.deleted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deleted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DeleteResponse>, I>>(base?: I): DeleteResponse {
    return DeleteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteResponse>, I>>(object: I): DeleteResponse {
    const message = createBaseDeleteResponse();
    message.deleted = object.deleted ?? false;
    return message;
  },
};

function createBaseCountResponse(): CountResponse {
  return { count: 0, dataVersion: 0 };
}

export const CountResponse: MessageFns<CountResponse> = {
  encode(message: CountResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.count !== 0) {
      writer.uint32(8).int64(message.count);
    }
    if (message.dataVersion !== 0) {
      writer.uint32(16).int64(message.dataVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CountResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.count = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dataVersion = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CountResponse>, I>>(base?: I): CountResponse {
    return CountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CountResponse>, I>>(object: I): CountResponse {
    const message = createBaseCountResponse();
    message.count = object.count ?? 0;
    message.dataVersion = object.dataVersion ?? 0;
    return message;
  },
};

function createBaseFieldMetadata(): FieldMetadata {
  return { name: "", label: "", fieldType: "" };
}

export const FieldMetadata: MessageFns<FieldMetadata> = {
  encode(message: FieldMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.label !== "") {
      writer.uint32(18).string(message.label);
    }
    if (message.fieldType !== "") {
      writer.uint32(26).string(message.fieldType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FieldMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fieldType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<FieldMetadata>, I>>(base?: I): FieldMetadata {
    return FieldMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FieldMetadata>, I>>(object: I): FieldMetadata {
    const message = createBaseFieldMetadata();
    message.name = object.name ?? "";
    message.label = object.label ?? "";
    message.fieldType = object.fieldType ?? "";
    return message;
  },
};

function createBaseFieldMetadataList(): FieldMetadataList {
  return { fields: [] };
}

export const FieldMetadataList: MessageFns<FieldMetadataList> = {
  encode(message: FieldMetadataList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.fields) {
      FieldMetadata.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FieldMetadataList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldMetadataList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fields.push(FieldMetadata.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<FieldMetadataList>, I>>(base?: I): FieldMetadataList {
    return FieldMetadataList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FieldMetadataList>, I>>(object: I): FieldMetadataList {
    const message = createBaseFieldMetadataList();
    message.fields = object.fields?.map((e) => FieldMetadata.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFieldValues(): FieldValues {
  return { field: "", values: [], dataVersion: 0 };
}

export const FieldValues: MessageFns<FieldValues> = {
  encode(message: FieldValues, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field !== "") {
      writer.uint32(10).string(message.field);
    }
    for (const v of message.values) {
      writer.uint32(18).string(v!);
    }
    if (message.dataVersion !== 0) {
      writer.uint32(24).int64(message.dataVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FieldValues {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldValues();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.field = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.values.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.dataVersion = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<FieldValues>, I>>(base?: I): FieldValues {
    return FieldValues.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FieldValues>, I>>(object: I): FieldValues {
    const message = createBaseFieldValues();
    message.field = object.field ?? "";
    message.values = object.values?.map((e) => e) || [];
    message.dataVersion = object.dataVersion ?? 0;
    return message;
  },
};

function createBaseBboxResponse(): BboxResponse {
  return { minLng: 0, minLat: 0, maxLng: 0, maxLat: 0, dataVersion: 0 };
}

export const BboxResponse: MessageFns<BboxResponse> = {
  encode(message: BboxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.minLng !== 0) {
      writer.uint32(9).double(message.minLng);
    }
    if (message.minLat !== 0) {
      writer.uint32(17).double(message.minLat);
    }
    if (message.maxLng !== 0) {
      writer.uint32(25).double(message.maxLng);
    }
    if (message.maxLat !== 0) {
      writer.uint32(33).double(message.maxLat);
    }
    if (message.dataVersion !== 0) {
      writer.uint32(40).int64(message.dataVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BboxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBboxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.minLng = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.minLat = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.maxLng = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.maxLat = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dataVersion = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<BboxResponse>, I>>(base?: I): BboxResponse {
    return BboxResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BboxResponse>, I>>(object: I): BboxResponse {
    const message = createBaseBboxResponse();
    message.minLng = object.minLng ?? 0;
    message.minLat = object.minLat ?? 0;
    message.maxLng = object.maxLng ?? 0;
    message.maxLat = object.maxLat ?? 0;
    message.dataVersion = object.dataVersion ?? 0;
    return message;
  },
};

function createBaseSpecies(): Species {
  return { commonName: "", scientificName: "" };
}

export const Species: MessageFns<Species> = {
  encode(message: Species, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.commonName !== "") {
      writer.uint32(10).string(message.commonName);
    }
    if (message.scientificName !== "") {
      writer.uint32(18).string(message.scientificName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Species {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpecies();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.commonName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scientificName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Species>, I>>(base?: I): Species {
    return Species.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Species>, I>>(object: I): Species {
    const message = createBaseSpecies();
    message.commonName = object.commonName ?? "";
    message.scientificName = object.scientificName ?? "";
    return message;
  },
};

function createBaseSighting(): Sighting {
  return {
    id: 0,
    commonNameIndex: undefined,
    count: undefined,
    latitude: 0,
    longitude: 0,
    countryCode: undefined,
    regionCode: undefined,
    observedAt: "",
  };
}

export const Sighting: MessageFns<Sighting> = {
  encode(message: Sighting, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.commonNameIndex !== undefined) {
      writer.uint32(16).uint32(message.commonNameIndex);
    }
    if (message.count !== undefined) {
      writer.uint32(24).int64(message.count);
    }
    if (message.latitude !== 0) {
      writer.uint32(33).double(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(41).double(message.longitude);
    }
    if (message.countryCode !== undefined) {
      writer.uint32(50).string(message.countryCode);
    }
    if (message.regionCode !== undefined) {
      writer.uint32(58).string(message.regionCode);
    }
    if (message.observedAt !== "") {
      writer.uint32(66).string(message.observedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Sighting {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSighting();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.commonNameIndex = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.count = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.latitude = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.longitude = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.countryCode = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.regionCode = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.observedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Sighting>, I>>(base?: I): Sighting {
    return Sighting.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Sighting>, I>>(object: I): Sighting {
    const message = createBaseSighting();
    message.id = object.id ?? 0;
    message.commonNameIndex = object.commonNameIndex ?? undefined;
    message.count = object.count ?? undefined;
    message.latitude = object.latitude ?? 0;
    message.longitude = object.longitude ?? 0;
    message.countryCode = object.countryCode ?? undefined;
    message.regionCode = object.regionCode ?? undefined;
    message.observedAt = object.observedAt ?? "";
    return message;
  },
};

function createBaseGroupedSighting(): GroupedSighting {
  return { commonNameIndex: undefined, countryCode: undefined, observedAt: undefined, count: 0, speciesCount: 0 };
}

export const GroupedSighting: MessageFns<GroupedSighting> = {
  encode(message: GroupedSighting, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.commonNameIndex !== undefined) {
      writer.uint32(8).uint32(message.commonNameIndex);
    }
    if (message.countryCode !== undefined) {
      writer.uint32(18).string(message.countryCode);
    }
    if (message.observedAt !== undefined) {
      writer.uint32(26).string(message.observedAt);
    }
    if (message.count !== 0) {
      writer.uint32(32).int64(message.count);
    }
    if (message.speciesCount !== 0) {
      writer.uint32(40).int64(message.speciesCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupedSighting {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupedSighting();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.commonNameIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.countryCode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.observedAt = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.count = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.speciesCount = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<GroupedSighting>, I>>(base?: I): GroupedSighting {
    return GroupedSighting.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupedSighting>, I>>(object: I): GroupedSighting {
    const message = createBaseGroupedSighting();
    message.commonNameIndex = object.commonNameIndex ?? undefined;
    message.countryCode = object.countryCode ?? undefined;
    message.observedAt = object.observedAt ?? undefined;
    message.count = object.count ?? 0;
    message.speciesCount = object.speciesCount ?? 0;
    return message;
  },
};

function createBaseSightingsResponse(): SightingsResponse {
  return { nameIndex: [], sightings: [], groups: [], total: 0, dataVersion: 0, nextCursor: undefined };
}

export const SightingsResponse: MessageFns<SightingsResponse> = {
  encode(message: SightingsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.nameIndex) {
      Species.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.sightings) {
      Sighting.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.groups) {
      GroupedSighting.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(32).int64(message.total);
    }
    if (message.dataVersion !== 0) {
      writer.uint32(40).int64(message.dataVersion);
    }
    if (message.nextCursor !== undefined) {
      writer.uint32(66).string(message.nextCursor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SightingsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSightingsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nameIndex.push(Species.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sightings.push(Sighting.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.groups.push(GroupedSighting.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.total = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dataVersion = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.nextCursor = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SightingsResponse>, I>>(base?: I): SightingsResponse {
    return SightingsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SightingsResponse>, I>>(object: I): SightingsResponse {
    const message = createBaseSightingsResponse();
    message.nameIndex = object.nameIndex?.map((e) => Species.fromPartial(e)) || [];
    message.sightings = object.sightings?.map((e) => Sighting.fromPartial(e)) || [];
    message.groups = object.groups?.map((e) => GroupedSighting.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.dataVersion = object.dataVersion ?? 0;
    message.nextCursor = object.nextCursor ?? undefined;
    return message;
  },
};

function createBaseVersionInfo(): VersionInfo {
  return { gitHash: "", buildDate: "", rustcVersion: "" };
}

export const VersionInfo: MessageFns<VersionInfo> = {
  encode(message: VersionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gitHash !== "") {
      writer.uint32(10).string(message.gitHash);
    }
    if (message.buildDate !== "") {
      writer.uint32(18).string(message.buildDate);
    }
    if (message.rustcVersion !== "") {
      writer.uint32(26).string(message.rustcVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VersionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVersionInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gitHash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.buildDate = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.rustcVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<VersionInfo>, I>>(base?: I): VersionInfo {
    return VersionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VersionInfo>, I>>(object: I): VersionInfo {
    const message = createBaseVersionInfo();
    message.gitHash = object.gitHash ?? "";
    message.buildDate = object.buildDate ?? "";
    message.rustcVersion = object.rustcVersion ?? "";
    return message;
  },
};

function createBaseSpeciesCount(): SpeciesCount {
  return { commonName: "", scientificName: "", count: 0 };
}

export const SpeciesCount: MessageFns<SpeciesCount> = {
  encode(message: SpeciesCount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.commonName !== "") {
      writer.uint32(10).string(message.commonName);
    }
    if (message.scientificName !== "") {
      writer.uint32(18).string(message.scientificName);
    }
    if (message.count !== 0) {
      writer.uint32(24).int64(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeciesCount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeciesCount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.commonName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scientificName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.count = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SpeciesCount>, I>>(base?: I): SpeciesCount {
    return SpeciesCount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeciesCount>, I>>(object: I): SpeciesCount {
    const message = createBaseSpeciesCount();
    message.commonName = object.commonName ?? "";
    message.scientificName = object.scientificName ?? "";
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseCountryStats(): CountryStats {
  return { countryCode: "", sightings: 0, lifers: 0 };
}

export const CountryStats: MessageFns<CountryStats> = {
  encode(message: CountryStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.countryCode !== "") {
      writer.uint32(10).string(message.countryCode);
    }
    if (message.sightings !== 0) {
      writer.uint32(16).int64(message.sightings);
    }
    if (message.lifers !== 0) {
      writer.uint32(24).int64(message.lifers);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CountryStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountryStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.countryCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sightings = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lifers = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CountryStats>, I>>(base?: I): CountryStats {
    return CountryStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CountryStats>, I>>(object: I): CountryStats {
    const message = createBaseCountryStats();
    message.countryCode = object.countryCode ?? "";
    message.sightings = object.sightings ?? 0;
    message.lifers = object.lifers ?? 0;
    return message;
  },
};

function createBaseTimelinePoint(): TimelinePoint {
  return { date: "", count: 0 };
}

export const TimelinePoint: MessageFns<TimelinePoint> = {
  encode(message: TimelinePoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    if (message.count !== 0) {
      writer.uint32(16).int64(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TimelinePoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTimelinePoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.count = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TimelinePoint>, I>>(base?: I): TimelinePoint {
    return TimelinePoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TimelinePoint>, I>>(object: I): TimelinePoint {
    const message = createBaseTimelinePoint();
    message.date = object.date ?? "";
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseStatsResponse(): StatsResponse {
  return {
    totalSightings: 0,
    totalLifers: 0,
    totalYearTicks: 0,
    totalCountryTicks: 0,
    totalSpecies: 0,
    totalCountries: 0,
    totalRegions: 0,
    hoursBirdingMinutes: 0,
    firstSightingDate: undefined,
    latestSightingDate: undefined,
    topSpecies: [],
    countryStats: [],
    dataVersion: 0,
    totalIndividuals: 0,
    totalDistanceKm: undefined,
    lifersTimeline: [],
    sightingsTimeline: [],
    longestStreakDays: 0,
  };
}

export const StatsResponse: MessageFns<StatsResponse> = {
  encode(message: StatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalSightings !== 0) {
      writer.uint32(8).int64(message.totalSightings);
    }
    if (message.totalLifers !== 0) {
      writer.uint32(16).int64(message.totalLifers);
    }
    if (message.totalYearTicks !== 0) {
      writer.uint32(24).int64(message.totalYearTicks);
    }
    if (message.totalCountryTicks !== 0) {
      writer.uint32(32).int64(message.totalCountryTicks);
    }
    if (message.totalSpecies !== 0) {
      writer.uint32(40).int64(message.totalSpecies);
    }
    if (message.totalCountries !== 0) {
      writer.uint32(48).int64(message.totalCountries);
    }
    if (message.totalRegions !== 0) {
      writer.uint32(56).int64(message.totalRegions);
    }
    if (message.hoursBirdingMinutes !== 0) {
      writer.uint32(64).int64(message.hoursBirdingMinutes);
    }
    if (message.firstSightingDate !== undefined) {
      writer.uint32(74).string(message.firstSightingDate);
    }
    if (message.latestSightingDate !== undefined) {
      writer.uint32(82).string(message.latestSightingDate);
    }
    for (const v of message.topSpecies) {
      SpeciesCount.encode(v!, writer.uint32(90).fork()).join();
    }
    for (const v of message.countryStats) {
      CountryStats.encode(v!, writer.uint32(98).fork()).join();
    }
    if (message.dataVersion !== 0) {
      writer.uint32(104).int64(message.dataVersion);
    }
    if (message.totalIndividuals !== 0) {
      writer.uint32(112).int64(message.totalIndividuals);
    }
    if (message.totalDistanceKm !== undefined) {
      writer.uint32(121).double(message.totalDistanceKm);
    }
    for (const v of message.lifersTimeline) {
      TimelinePoint.encode(v!, writer.uint32(130).fork()).join();
    }
    for (const v of message.sightingsTimeline) {
      TimelinePoint.encode(v!, writer.uint32(138).fork()).join();
    }
    if (message.longestStreakDays !== 0) {
      writer.uint32(144).int64(message.longestStreakDays);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalSightings = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalLifers = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalYearTicks = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalCountryTicks = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.totalSpecies = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalCountries = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalRegions = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.hoursBirdingMinutes = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.firstSightingDate = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.latestSightingDate = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.topSpecies.push(SpeciesCount.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.countryStats.push(CountryStats.decode(reader, reader.uint32()));
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.dataVersion = longToNumber(reader.int64());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.totalIndividuals = longToNumber(reader.int64());
          continue;
        }
        case 15: {
          if (tag !== 121) {
            break;
          }

          message.totalDistanceKm = reader.double();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.lifersTimeline.push(TimelinePoint.decode(reader, reader.uint32()));
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.sightingsTimeline.push(TimelinePoint.decode(reader, reader.uint32()));
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.longestStreakDays = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StatsResponse>, I>>(base?: I): StatsResponse {
    return StatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatsResponse>, I>>(object: I): StatsResponse {
    const message = createBaseStatsResponse();
    message.totalSightings = object.totalSightings ?? 0;
    message.totalLifers = object.totalLifers ?? 0;
    message.totalYearTicks = object.totalYearTicks ?? 0;
    message.totalCountryTicks = object.totalCountryTicks ?? 0;
    message.totalSpecies = object.totalSpecies ?? 0;
    message.totalCountries = object.totalCountries ?? 0;
    message.totalRegions = object.totalRegions ?? 0;
    message.hoursBirdingMinutes = object.hoursBirdingMinutes ?? 0;
    message.firstSightingDate = object.firstSightingDate ?? undefined;
    message.latestSightingDate = object.latestSightingDate ?? undefined;
    message.topSpecies = object.topSpecies?.map((e) => SpeciesCount.fromPartial(e)) || [];
    message.countryStats = object.countryStats?.map((e) => CountryStats.fromPartial(e)) || [];
    message.dataVersion = object.dataVersion ?? 0;
    message.totalIndividuals = object.totalIndividuals ?? 0;
    message.totalDistanceKm = object.totalDistanceKm ?? undefined;
    message.lifersTimeline = object.lifersTimeline?.map((e) => TimelinePoint.fromPartial(e)) || [];
    message.sightingsTimeline = object.sightingsTimeline?.map((e) => TimelinePoint.fromPartial(e)) || [];
    message.longestStreakDays = object.longestStreakDays ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
